apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: monitoring-crd
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-monitoring-crd
  targets:
  - name: monitoring
    clusterSelector:
      matchLabels:
        monitoring: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: monitoring
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-monitoring
  targets:
  - name: monitoring
    clusterSelector:
      matchLabels:
        monitoring: enabled