controller:
  pvc:
    capacity: 1Gi
    enabled: true
  ranchersso:
    enabled: true
k3s:
  enabled: true
  runtimePath: /run/k3s/containerd/containerd.sock
manager:
  svc:
    type: ClusterIP
psp: true
rbac: true